### ISSUE TITLE
change name scheme

### ISSUE THREAD

**Issue by bkardell** [bkardell/common-panel#13]
I've been working under the fully dashed name kind of scheme which means we have dash after panel.  This is pretty readable, but it starts getting tough to make the mental leaps toward 'what would this look like as a real proposal and to write about it in the draft.

I'd like to consider using only a prefix dash scheme which  make this pretty simple to grok:
`<common-panel-set>` would change to `<common-panelset>` and as a proposal you can talk about it simply as "panelset" and remove the prefix.  Likewise, `<common-panel-title>` would become `<common-paneltitle>` which has readability issues IMO and suggests we should come up with a better name...

**Comment by LJWatson** [comment]
Good idea.

Using common-elementname (for example common-panelset) as the format for the custom elements used in the prototypes, and elementname (for example panelset) as we write the spec text, will help make everything more understandable.

We'll then be in a better position to re-organise the spec by element/attribute name, instead of panel variety.

**Comment by chaals** [comment]
This appears to have been done…

**Comment by LJWatson** [comment]
It has been done. We have `<panel>`, `<paneltitle>` and `<panelset>` in the current draft of the spec.
