### ISSUE TITLE
Why <paneltitle>

### ISSUE THREAD

**Issue by brucelawson** [bkardell/common-panel#29]
.. and not [header] inside [panel] ? 

More new elements makes implementation harder - test suites, etc? also gives better fallback, imo

**Comment by bkardell** [comment]
Yeah this was discussed at some length on teleconf on at least two occasion (mostly around whether the final dom should call that a heading or not) - it began in author form as an attribute, but issue #1 changed our minds on that... Very likely we should sit down and record the rationale for what we landed on, but I'd definitely need @stevefaulkner and @LjWatson support on that..

**Comment by brucelawson** [comment]
yes, "record the rationale for what we landed on". When you're on the TV chat-show circuit, you know you'll be asked this time and time again.

**Comment by bkardell** [comment]
Well, definitely you can say it's not self-evident at first glance why it is not for example, just a section with heading, or a summary detail or any number of other things either expressed by the author that way, or ultimately built into.  Given that logic tends to build on decisions and assumptions the choices seem to be that we leave it as is and ultimately when the questions inevitably come we have to keep explaining all the way down in order for someone to point out some nit in the logic, or we could just do it once and say "have at it folks".  The later seems more efficient to me :)

**Comment by chaals** [comment]
Yeah, `<header>` "feels" like a page-level element. But it isn't, and might make sense…

**Comment by stevefaulkner** [comment]
I can't remember,why but do remember thinking that where native elements could be used they should...

**Comment by hhubbell** [comment]
However, `<paneltitle>` adds more than just `<header>` like semantics -- it tells the browser "this part should remain visible even if the panel is collapsed"

**Comment by stevefaulkner** [comment]
@hhubbell couldn't that be expressed as a simple CSS UA rule?  first header in panel is always visible?

**Comment by bkardell** [comment]
Ok, so most of this discussion happened verbally, but I do have a couple of conversations in my skype history that record why we had the conversation in the first place, I'm skipping a lot and mixing recollections into something in order to reassemble that looks like enough to give a sensible history... _please_ feel free to correct me if I am misrepresenting anything.

First I put together a proposal which laid it out like this: `<panel title="Weather">...</panel>`.  Then I created what I hoped was an accessible prototype which illustrated the responsive switching of visualization.  However, my ARIA was based on looking at a couple of examples and it turned out that they're all doing things a little differently.  Not being sure it is 'right' or really how to test it well, I turn to Steve and Leonie.  Surprisingly we all arrived at slightly different answers initially, so we resolve to have a skype conversation and sort it out.  It was a _long_ conversation with lots of debate focusing on (this is important) what the _built_ dom should look like (note, not the author specified dom - the functional one generated in upgrade).  Below is a _radically_ simplified recollection with relevant highlights (and skipping a lot of aria talk and some other HTML things we considered)

steve: Is it a `<section>` and `<header>`?  

leonie: If they are tab controls they probably aren't headers, that would be confusing.

brian: I don't think so either because: Why do we have  `<summary>` and `<detail>`?  why not just  `<section>` and `<header>`?  Because, it's something else - it says something about the relationship of control and has pseudo-elements and so on.   You could probably as accurately ask why isn't it just `<summary>` and `<detail>`
steve: Ok, why isn't it?
brian: Because it's something else - it has it's own nature, optional attributes and dom methods and default styling and built in behavior and relationships that neither of the above have.  It could _contain_ those, or it could (maybe even should) _extend_ those (if that winds up possible) but it isn't itself those things.  Just because you have the word "bird" doesn't mean you shouldn't also have the words "duck" or "pigeon". 

And so in the final DOM (basically the shadow dom if we had that) we wound up not having those.  Then, following discussion of Issue #1 we had this chat..

brian:  So I guess we're going to use an element for panel title after all..

steve: why not just use a <header>?

brian:  title is currently (originally) an attribute because the only user-settable HTML input that’s valid is text. If it becomes an element then you have to understand bits of the final dom to understand what you can and can't put inside it - for example - if `<common-panel-title>` becomes `<heading>` then would you have to understand that either the whole panel header is not a `<heading>` or would we have to make the whole panel header (the final one) a heading and take the content out of your heading and put it into a certain slot in that one?  Would it actually add any benefit in the event it didn't upgrade since at that point its parent element is just an unknown element?

Again, @stevefaulkner and @LjWatson please correct or fill in as you think helpful.

**Comment by stevefaulkner** [comment]
@bkardell you have provided a much more comprehensive account of discussions than my addled brain recalls :-)

**Comment by chaals** [comment]
Hmm. Seems reasonable to close this…

**Comment by LJWatson** [comment]
@Chaals. Agreed.
