### ISSUE TITLE
Remove aria-controls from basic panel prototype

### ISSUE THREAD

**Issue by LJWatson** [bkardell/common-panel#3]
Suggest removing aria-controls from the common-panel-header div in the basic panel example. The header doesn't control the panel content (interacting with the header doesn't cause a change to the panel content).

**Comment by bkardell** [comment]
Currently what I have here is a constant recipe, but that might be not enough...

It's, at least theoretically possible that one could set attributes or properties for collapsing or removing a panel at runtime.  We should be clear in the spec and make sure we create some IDL definition about whether those are [Reflect].   if we decide that those attributes should take effect if set later (I kind of think they should because, for example, you could place a panel into a panelset to add a tab - like you do in your browser and then it automatically has to become expandable/collapsable)

@LjWatson,  I assume what we're saying is that if you have either attribute set the aria-controls is correct, otherwise it's not?

**Comment by LJWatson** [comment]
For the prototype panels that have expand/collapse capability, aria-controls would be appropriate. It needs to be applied to the focusable element that is the control though, rather than its parent container.

**Comment by bkardell** [comment]
so, the header part is focusable and it is the thing which says 'aria-controls' and that points to the content part which is also focusable and is the thing being aria-hidden/aria-expanded... Is that right?
