### ISSUE TITLE
Move to WebSpecs

### ISSUE THREAD

**Issue by darobin** [bkardell/common-panel#8]
If you're up for it, I think it ought to live there. I am soon to support ReSpec too.

**Comment by bkardell** [comment]
Yep, we'll gladly move it soon.  I'd like to have it in a state where we have a few people who agree that this is the proposal we'd like to make - it's generally how I think normal human productivity and communication most naturally works.  I expect it's getting pretty close.

**Comment by LJWatson** [comment]
+1 to moving it to webspecs.org/

+1 to doing a bit more work on it first. If we can tidy up some of the terminology inconsistencies (especially between the spec and the prototypes), and do some reorganisation of the spec so it is broken down by element/attribute (instead of panel variety), it'll help head off a lot of confusion.

**Comment by LJWatson** [comment]
@darobin if you have guidance on the best way to organise the spec so it starts to feel a little bit more like the real thing, that'd be most useful!

**Comment by bkardell** [comment]
@darobin are we getting close to where webspecs is ready for us?
